apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout
  namespace: amarshop
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: amarshop/backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: amarshop-config
            - secretRef:
                name: amarshop-secrets
  strategy:
    blueGreen:
      activeService: backend-service
      previewService: backend-preview-service
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 600
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-rollout
  namespace: amarshop
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: amarshop/frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: amarshop-config
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {duration: 5m}
        - setWeight: 30
        - pause: {duration: 5m}
        - setWeight: 60
        - pause: {duration: 5m}
        - setWeight: 100
